name: groupoids
version: "1.69"
license: "GPL-2.0-or-later"
date: 2021-11-15
description: |
    Calculations with finite groupoids and their homomorphisms

authors:
    - name: Emma J. Moore
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.10.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2019.02.22"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "GAPDoc"
      version: ">= 1.6.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "fga"
      version: ">= 1.4.0"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "utils"
      version: ">= 0.63"
      url: "https://gap-packages.github.io/utils"

suggested-pkgs:
    - name: "semigroups"
      version: ">= 3.1.1"
      url: "https://gap-packages.github.io/Semigroups"

www: https://gap-packages.github.io/groupoids/
readme: README.md
packageinfo: https://gap-packages.github.io/groupoids/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/groupoids/releases/download/v1.69/groupoids-1.69.tar.gz

abstract: |
    The groupoids package provides a collection of functions for computing with finite groupoids, graph of groups, and graphs of groupoids. These are based on the more basic structures of magmas with objects and their mappings. It provides functions for normal forms of elements in Free Products with Amalgamation and in HNN extensions. Up until April 2017 this package was named Gpd.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    magma with objects, groupoid, graph of groups, free product with amalgamation, HNN extension, automorphisms.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MW21</span>]   <b class='BibAuthor'>Moore, E. J. and Wensley, C.</b>,
     <i class='BibTitle'>groupoids, Calculations with finite groupoids and their homomorphisms,
             Version 1.69</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/groupoids/">https://gap-packages.github.io/groupoids/</a></span>.
    </p>
    

bibtex: |
    @misc{ groupoids1.69,
      author =           {Moore, E. J. and Wensley, C.},
      title =            {{groupoids},  Calculations  with  finite groupoids and
                          their homomorphisms, {V}ersion 1.69},
      month =            {Nov},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href      {https://gap-packages.github.io/groupoids/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{groupoids/}}},
      keywords =         {magma  with  objects;  groupoid; graph of groups; free
                          product     with    amalgamation;    HNN    extension;
                          automorphisms},
      printedkey =       {MW21}
    }

