# groupoids, chapter 9
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("groupoids09.tst");

# doc/tecnotes.xml:62-104
gap> CategoriesOfObject( Gd8 );
[ "IsListOrCollection", "IsCollection", "IsExtLElement", 
  "CategoryCollections(IsExtLElement)", "IsExtRElement", 
  "CategoryCollections(IsExtRElement)", 
  "CategoryCollections(IsMultiplicativeElement)", "IsGeneralizedDomain", 
  "IsDomainWithObjects", 
  "CategoryCollections(IsMultiplicativeElementWithObjects)", 
  "CategoryCollections(IsMultiplicativeElementWithObjectsAndOnes)", 
  "CategoryCollections(IsMultiplicativeElementWithObjectsAndInverses)", 
  "CategoryCollections(IsGroupoidElement)", "IsMagmaWithObjects", 
  "IsSemigroupWithObjects", "IsMonoidWithObjects", "IsGroupoid" ]
gap> FamilyObj( Gd8 );                     
<Family: "CollectionsFamily(...)">
gap> Display(last);   
name:
    CollectionsFamily(...)
required filters:
    IsCollection
implied filters:
    IsListOrCollection
    IsCollection
    IsExtLElement
    CategoryCollections(IsExtLElement)
    IsExtRElement
    CategoryCollections(IsExtRElement)
    CategoryCollections(IsMultiplicativeElement)
    IsOddAdditiveNestingDepthObject
    CategoryCollections(IsMultiplicativeElementWithObjects)
    CategoryCollections(IsMultiplicativeElementWithObjectsAndOnes)
    CategoryCollections(IsMultiplicativeElementWithObjectsAndInverses)
    CategoryCollections(IsGroupoidElement)
gap> KnownAttributesOfObject( Gd8 ); 
[ "Name", "Size", "ObjectList", "Pieces", "GeneratorsOfMagmaWithObjects", 
  "RaysOfGroupoid", "GeneratorsOfGroupoid", "DiscreteTrivialSubgroupoid" ]
gap> KnownTruePropertiesOfObject( Gd8 ); 
[ "IsNonTrivial", "IsFinite", "IsDuplicateFree", "IsAssociative", 
  "IsSinglePieceDomain", "IsDirectProductWithCompleteDigraphDomain" ]
gap> RepresentationsOfObject( Gd8 );
[ "IsComponentObjectRep", "IsAttributeStoringRep", "IsMWOSinglePieceRep" ]
gap> RepresentationsOfObject( U5 ); 
[ "IsComponentObjectRep", "IsAttributeStoringRep", "IsPiecesRep" ]

# doc/tecnotes.xml:108-118
gap> e1;
[(5,6,7,8) : -7 -> -8]
gap> CategoriesOfObject( e1 );
[ "IsExtLElement", "IsExtRElement", "IsMultiplicativeElement", 
  "IsMultiplicativeElementWithObjects", 
  "IsMultiplicativeElementWithObjectsAndOnes", 
  "IsMultiplicativeElementWithObjectsAndInverses", "IsGroupoidElement" ]
gap> FamilyObj( e1 );
<Family: "IsGroupoidElementFamily">

# doc/tecnotes.xml:165-224
gap> hom9;
groupoid homomorphism : Gd8 -> Kk4
[ [ [(5,6,7,8) : -9 -> -9], [(5,7) : -9 -> -9], [() : -9 -> -8], 
      [() : -9 -> -7], [() : -9 -> -6] ], 
  [ [(1,4)(2,3) : -14 -> -14], [() : -14 -> -14], [(1,2,3) : -14 -> -13], 
      [(1,2,4) : -14 -> -12], [(1,3,4) : -14 -> -11] ] ]
gap> CategoriesOfObject( hom9 );
[ "IsExtLElement", "IsExtRElement", "IsMultiplicativeElement", 
  "IsMultiplicativeElementWithOne", "IsMultiplicativeElementWithInverse", 
  "IsAssociativeElement", "IsGeneralMapping", "IsSPGeneralMapping", 
  "IsGeneralMappingWithObjects", "IsSPGeneralMappingWithObjects", 
  "IsGroupoidHomomorphism" ]
gap> FamilyObj( hom9 );
<Family: "GroupoidHomomorphismFamily">
gap> Display( last );
name:
    GroupoidHomomorphismFamily
required filters:
    IsGroupoidHomomorphism
implied filters:
    CanEasilyCompareElements
    HasCanEasilyCompareElements
    CanEasilySortElements
    HasCanEasilySortElements
    IsExtLElement
    IsExtRElement
    IsMultiplicativeElement
    IsMultiplicativeElementWithOne
    IsMultiplicativeElementWithInverse
    IsAssociativeElement
    IsGeneralMapping
    IsSPGeneralMapping
    RespectsMultiplication
    HasRespectsMultiplication
    IsGeneralMappingWithObjects
    IsSPGeneralMappingWithObjects
    IsGroupoidHomomorphism
gap> FamilyObj( hom9 ) = FamilyObj( aut1 );
true
gap> KnownTruePropertiesOfObject( hom9 );
[ "CanEasilyCompareElements", "CanEasilySortElements", 
  "RespectsMultiplication", "IsGroupWithObjectsHomomorphism", 
  "IsGeneralMappingToSinglePiece", "IsGeneralMappingFromSinglePiece", 
  "IsInjectiveOnObjects", "IsSurjectiveOnObjects" ]
gap> KnownTruePropertiesOfObject( aut1 );
[ "CanEasilyCompareElements", "CanEasilySortElements", "IsEndoGeneralMapping",
  "RespectsMultiplication", "IsGroupWithObjectsHomomorphism", 
  "IsGeneralMappingToSinglePiece", "IsGeneralMappingFromSinglePiece", 
  "IsInjectiveOnObjects", "IsSurjectiveOnObjects", 
  "IsEndomorphismWithObjects", "IsAutomorphismWithObjects", 
  "IsGroupoidAutomorphismByObjectPerm" ]
gap> KnownAttributesOfObject( hom9 );
[ "Range", "Source", "MappingGeneratorsImages", "MappingToSinglePieceData", 
  "ImagesOfObjects", "ImageElementsOfRays", "RootGroupHomomorphism" ]
gap> KnownAttributesOfObject( aut1 );
[ "Order", "Range", "Source", "MappingGeneratorsImages", "AutomorphismDomain",
  "MappingToSinglePieceData", "ImagesOfObjects", "ImageElementsOfRays", 
  "RootGroupHomomorphism" ]

#
gap> STOP_TEST("groupoids09.tst", 1);
